Repository TripMingle/Back-End-Application, pull requests merged in 2024-08, with the labels that each got.

#78 [refactor] 클라이언트 요구 사항 반영 - 로그인 시 회원 여부 필드 추가
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/application/service/KakaoService.java
  src/main/java/com/example/tripmingle/dto/etc/KakaoLoginDTO.java
Labels: fix, refactor

#79 [Feat SWM-231] 액세스 토큰 재발급 로직 개발 및 로그인/회원가입 시 리프레쉬토큰 헤더로 반환
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/application/facadeService/AuthFacadeService.java
  src/main/java/com/example/tripmingle/application/service/AuthService.java
  src/main/java/com/example/tripmingle/application/service/KakaoService.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/ExpiredRefreshTokenException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/etc/KakaoLoginDTO.java
  src/main/java/com/example/tripmingle/dto/res/auth/TokenDTO.java
  src/main/java/com/example/tripmingle/port/in/AuthUseCase.java
Labels: feat, refactor

#81 [Hotfix/refactor] userImageUrl에 boardImageUrl이 들어가는 로직 수정
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
Labels: documentation, hotfix

#82 [Refactor/SWM-232] jwt 토큰 expose headers에 추가
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
Labels: refactor

#83 [Refactor/SWM-233] 닉네임 중복 커스텀 에러 처리 추가
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/application/facadeService/AuthFacadeService.java
  src/main/java/com/example/tripmingle/application/service/AuthService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/NickNameDuplicationException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/port/in/AuthUseCase.java
Labels: refactor

#80 [Refactor/SWM-221] 유저 점수 온도에서 점수제로 변경
  src/main/java/com/example/tripmingle/entity/User.java
Labels: refactor

#84 [Refactor/SWM-238] 닉네임 중복 에러 status 코드 할당되지 않은 status로 변경
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
Labels: refactor

#85 [refactor/SWM-239] 회원가입시 자기소개 추가
  src/main/java/com/example/tripmingle/application/service/KakaoService.java
  src/main/java/com/example/tripmingle/dto/req/user/AdditionalUserDetailReqDTO.java
Labels: refactor

#87 [Refactor/SWM-241] 닉네임 중복 에러 status 452 -> 409로 변경
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
Labels: refactor

#88 [Feat/SWM-237] 채팅 마지막 인덱스 필드 추가
  src/main/java/com/example/tripmingle/adapter/out/ChatPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/ChatRoomFacadeService.java
  src/main/java/com/example/tripmingle/application/service/ChatService.java
  src/main/java/com/example/tripmingle/common/constants/Constants.java
  src/main/java/com/example/tripmingle/entity/ChatRoomUser.java
  src/main/java/com/example/tripmingle/port/out/ChatPersistPort.java
Labels: feat
