Repository TripMingle/Back-End-Application, pull requests merged in 2024-07, with the labels that each got.

#39 [Feat/SWM-131] 매칭서버에 유저 추가 로직 비동기 로직 작성
  src/main/java/com/example/tripmingle/TripMingleApplication.java
  src/main/java/com/example/tripmingle/adapter/in/MatchingController.java
  src/main/java/com/example/tripmingle/adapter/in/RedisMessageSubscriber.java
  src/main/java/com/example/tripmingle/adapter/out/MessagePublisher.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/MatchingService.java
  src/main/java/com/example/tripmingle/common/config/async/AsyncConfig.java
  src/main/java/com/example/tripmingle/common/config/redis/RedisConfig.java
  src/main/java/com/example/tripmingle/dto/etc/UserPersonalityIdPublishDTO.java
  src/main/java/com/example/tripmingle/port/in/MatchingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PublishPort.java
Labels: feat

#40 [Feat/SWM-127] 매칭서버 리팩터링 및 유저성향 수정로직 작성
  src/main/java/com/example/tripmingle/adapter/in/MatchingController.java
  src/main/java/com/example/tripmingle/adapter/in/RedisMessageSubscriber.java
  src/main/java/com/example/tripmingle/adapter/out/MatchingAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/MessagePublisher.java
  src/main/java/com/example/tripmingle/adapter/out/UserPersonalityPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/MatchingService.java
  src/main/java/com/example/tripmingle/application/service/UserPersonalityService.java
  src/main/java/com/example/tripmingle/common/config/redis/RedisConfig.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/MatchingServerException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/messageHandler/PubsubMessageHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/etc/DeleteUserPersonalityPublishDTO.java
  src/main/java/com/example/tripmingle/dto/etc/UserPersonalityReCalculatePublishDTO.java
  src/main/java/com/example/tripmingle/dto/res/matching/AddUserResDTO.java
  src/main/java/com/example/tripmingle/entity/UserPersonality.java
  src/main/java/com/example/tripmingle/port/in/MatchingUseCase.java
  src/main/java/com/example/tripmingle/port/out/MatchingPort.java
  src/main/java/com/example/tripmingle/port/out/PublishPort.java
  src/main/java/com/example/tripmingle/port/out/UserPersonalityPersistPort.java
  src/main/java/com/example/tripmingle/repository/UserPersonalityRepository.java
Labels: feat, refactor

#41 [Feat/SWM-182] swagger 설정
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/in/BoardScheduleController.java
  src/main/java/com/example/tripmingle/adapter/in/CountryController.java
  src/main/java/com/example/tripmingle/adapter/in/HealthController.java
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/adapter/in/MapController.java
  src/main/java/com/example/tripmingle/adapter/in/MatchingController.java
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/in/UserScheduleController.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feat

#42 refactor: 스웨거 Operation 적용 및 Controller 반환값 통일
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/adapter/in/HealthController.java
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
Labels: refactor

#45 feat: 채팅서버에서 어플리케이션 서버로 채팅 관련 api 마이그레이션
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/ChatController.java
  src/main/java/com/example/tripmingle/adapter/in/ChatRoomController.java
  src/main/java/com/example/tripmingle/adapter/out/ChatPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/ChatRoomUserPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/GroupChatRoomPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/OneOnOneChatRoomPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ChatFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ChatRoomFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ScheduleFacadeService.java
  src/main/java/com/example/tripmingle/application/service/ChatRoomService.java
  src/main/java/com/example/tripmingle/application/service/ChatService.java
  src/main/java/com/example/tripmingle/application/service/UserService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/AlreadyExistsChatRoomException.java
  src/main/java/com/example/tripmingle/common/exception/AlreadyExistsChatRoomUserException.java
  src/main/java/com/example/tripmingle/common/exception/ChatRoomNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/ChatRoomUserNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/OneOnOneChatRoomNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/chat/CreateGroupChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/chat/CreateOneOnOneChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/chat/EnterGroupChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/chat/ExitGroupChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/chat/ExitOneOnOneChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/CreateChatRoomResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/CreateOneOnOneChatRoomResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/EnterGroupChatRoomResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/ExitGroupChatRoomResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/ExitOneOnOneChatRoomResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/GetAllChatMessagesResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/GetChatMessageResDTO.java
  src/main/java/com/example/tripmingle/entity/ChatMessage.java
  src/main/java/com/example/tripmingle/entity/ChatRoomType.java
  src/main/java/com/example/tripmingle/entity/ChatRoomUser.java
  src/main/java/com/example/tripmingle/entity/GroupChatRoom.java
  src/main/java/com/example/tripmingle/entity/OneOnOneChatRoom.java
  src/main/java/com/example/tripmingle/port/in/ChatRoomUseCase.java
  src/main/java/com/example/tripmingle/port/in/ChatUseCase.java
  src/main/java/com/example/tripmingle/port/out/ChatPersistPort.java
  src/main/java/com/example/tripmingle/port/out/ChatRoomUserPersistPort.java
  src/main/java/com/example/tripmingle/port/out/GroupChatRoomPersistPort.java
  src/main/java/com/example/tripmingle/port/out/OneOnOneChatRoomPersistPort.java
  src/main/java/com/example/tripmingle/repository/ChatRepository.java
  src/main/java/com/example/tripmingle/repository/ChatRoomUserRepository.java
  src/main/java/com/example/tripmingle/repository/GroupChatRoomRepository.java
  src/main/java/com/example/tripmingle/repository/OneOnOneChatRoomRepository.java
Labels: feat

#46 [Feat/SWM-162] S3 설정 및 나라 사진 관련 API 작성
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/in/CountryController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/ChatPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/CountryImagePersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/CountryPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/S3StorageAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/CountryFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/application/service/CountryImageService.java
  src/main/java/com/example/tripmingle/application/service/CountryService.java
  src/main/java/com/example/tripmingle/application/service/S3Service.java
  src/main/java/com/example/tripmingle/common/config/s3/S3Config.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/config/swagger/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/CountryImageNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/CountryNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/S3Exception.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/country/UploadCountryImageReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/count/GetCountriesResDTO.java
  src/main/java/com/example/tripmingle/dto/res/country/GetCountriesResDTO.java
  src/main/java/com/example/tripmingle/dto/res/country/UploadCountryImageResDTO.java
  src/main/java/com/example/tripmingle/entity/Board.java
  src/main/java/com/example/tripmingle/entity/ChatMessage.java
  src/main/java/com/example/tripmingle/entity/CountryImage.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/in/CountryUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardPersistPort.java
  src/main/java/com/example/tripmingle/port/out/CountryImagePersistPort.java
  src/main/java/com/example/tripmingle/port/out/CountryPersistPort.java
  src/main/java/com/example/tripmingle/port/out/S3StoragePort.java
  src/main/java/com/example/tripmingle/repository/BoardRepository.java
  src/main/java/com/example/tripmingle/repository/ChatRepository.java
  src/main/java/com/example/tripmingle/repository/CountryImageRepository.java
  src/main/java/com/example/tripmingle/repository/CountryRepository.java
  src/main/resources/application.yml
Labels: feat

#48 refactor: 채팅방 관련 API 리팩토링
  src/main/java/com/example/tripmingle/adapter/in/ChatRoomController.java
  src/main/java/com/example/tripmingle/adapter/out/ChatRoomUserPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/GroupChatRoomPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/OneOnOneChatRoomPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/ChatRoomFacadeService.java
  src/main/java/com/example/tripmingle/application/service/ChatRoomService.java
  src/main/java/com/example/tripmingle/dto/req/chat/CreateOneOnOneChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/chat/EnterGroupChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/chat/EnterOneOnOneChatRoomReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/CreateChatRoomResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/EnterOneOnOneChatRoomResDTO.java
  src/main/java/com/example/tripmingle/entity/ChatRoomUser.java
  src/main/java/com/example/tripmingle/entity/OneOnOneChatRoom.java
  src/main/java/com/example/tripmingle/port/in/ChatRoomUseCase.java
  src/main/java/com/example/tripmingle/port/out/ChatRoomUserPersistPort.java
  src/main/java/com/example/tripmingle/port/out/GroupChatRoomPersistPort.java
  src/main/java/com/example/tripmingle/port/out/OneOnOneChatRoomPersistPort.java
  src/main/java/com/example/tripmingle/repository/ChatRoomUserRepository.java
  src/main/java/com/example/tripmingle/repository/GroupChatRoomRepository.java
  src/main/java/com/example/tripmingle/repository/OneOnOneChatRoomRepository.java
Labels: refactor

#49 [Feat/SWM-189] 대륙 사진 관련 API 개발
  src/main/java/com/example/tripmingle/adapter/in/ContinentController.java
  src/main/java/com/example/tripmingle/adapter/out/CacheManagerAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/ContinentPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ContinentFacadeService.java
  src/main/java/com/example/tripmingle/application/service/ContinentService.java
  src/main/java/com/example/tripmingle/application/service/MatchingService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/ContinentNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/dto/res/country/GetContinentsResDTO.java
  src/main/java/com/example/tripmingle/entity/Continent.java
  src/main/java/com/example/tripmingle/port/in/ContinentUseCase.java
  src/main/java/com/example/tripmingle/port/out/CacheManagerPort.java
  src/main/java/com/example/tripmingle/port/out/ContinentPersistPort.java
  src/main/java/com/example/tripmingle/port/out/MatchingPort.java
  src/main/java/com/example/tripmingle/repository/ContinentRepository.java
Labels: feat

#51 [Feat/SWM-190] 나라 조회로직 캐싱 구현
  src/main/java/com/example/tripmingle/adapter/in/ContinentController.java
  src/main/java/com/example/tripmingle/adapter/out/CacheManagerAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/CountryFacadeService.java
  src/main/java/com/example/tripmingle/application/service/CountryService.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/res/country/GetContinentsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/country/GetCountriesResDTO.java
  src/main/java/com/example/tripmingle/port/out/CacheManagerPort.java
Labels: feat

#52 [Fix/SWM-190] 오류수정
  src/main/java/com/example/tripmingle/adapter/out/CacheManagerAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/dto/etc/UpdateBoardDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/CreateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/UpdateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/entity/Board.java
  src/main/java/com/example/tripmingle/entity/UserPersonality.java
Labels: fix

#53 [feat/SWM-125] : 유저-게시판 매칭 서버 구현
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/CountryController.java
  src/main/java/com/example/tripmingle/adapter/in/MatchingController.java
  src/main/java/com/example/tripmingle/adapter/in/RedisMessageSubscriber.java
  src/main/java/com/example/tripmingle/adapter/out/CacheManagerAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/MessagePublisher.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/MatchingService.java
  src/main/java/com/example/tripmingle/application/service/UserPersonalityService.java
  src/main/java/com/example/tripmingle/common/config/redis/RedisConfig.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/etc/MatchingBoardPublishDTO.java
  src/main/java/com/example/tripmingle/dto/req/matching/MatchingBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/matching/PostUserPersonalityReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/matching/MatchingBoardResDTO.java
  src/main/java/com/example/tripmingle/entity/UserPersonality.java
  src/main/java/com/example/tripmingle/port/in/MatchingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PublishPort.java
Labels: feat

#54 [Feat/SWM-193] 캐싱 소요시간 측정 테스트코드 작성
  src/main/java/com/example/tripmingle/application/facadeService/CountryFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/MatchingService.java
  src/main/java/com/example/tripmingle/dto/req/matching/PostUserPersonalityReqDTO.java
  src/test/java/com/example/tripmingle/application/facadeService/CountryFacadeServiceTest.java
  src/test/java/com/example/tripmingle/application/facadeService/MatchingFacadeServiceTest.java
  src/test/resources/application.yml
Labels: feat

#56 [Feat/SWM-202] 유저성향 생성 및 변경 로직 리팩토링
  src/main/java/com/example/tripmingle/adapter/in/MatchingController.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/port/in/MatchingUseCase.java
  src/main/resources/application.yml
  src/test/java/com/example/tripmingle/application/facadeService/MatchingFacadeServiceTest.java
Labels: refactor

#57 [Feat/SWM-203]
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/in/MatchingController.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/common/constants/Constants.java
Labels: refactor

#58 [Feat] 포스팅 댓글 수 동시성 제어 적용 및 자잘한 validation 추가
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/InvalidPostingCommentAccess.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/dto/req/posting/DeletePostingCommentReqDTO.java
  src/main/java/com/example/tripmingle/port/in/PostingCommentUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
  src/main/java/com/example/tripmingle/repository/PostingRepository.java
  src/test/java/com/example/tripmingle/application/facadeService/PostingFacadeServiceTest.java
Labels: feat

#60 [Feat/SWM-203] 오류수정
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/repository/BoardRepository.java
Labels: fix

#61 add Readme file for ci test
  README.md
Labels: documentation

#62 modify readme file for ci test
  README.md
Labels: documentation

#64 test: cicd를 위한 health check api
  src/main/java/com/example/tripmingle/adapter/in/HealthController.java
Labels: feat

#65 [Hotfix] 포스팅 핫픽스
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/dto/res/posting/GetAllLikedPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/GetThumbNailPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/GetThumbNailPostingsResDTO.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
Labels: feat

#67 [Refactor]: 채팅방 및 채팅 로직 리팩토링
  src/main/java/com/example/tripmingle/adapter/in/ChatController.java
  src/main/java/com/example/tripmingle/adapter/in/ChatRoomController.java
  src/main/java/com/example/tripmingle/adapter/out/ChatPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/ChatFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ChatRoomFacadeService.java
  src/main/java/com/example/tripmingle/application/service/ChatService.java
  src/main/java/com/example/tripmingle/dto/req/chat/GetAllChatMessageReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/GetAllChatMessagesResDTO.java
  src/main/java/com/example/tripmingle/dto/res/chat/GetChatMessageResDTO.java
  src/main/java/com/example/tripmingle/entity/ChatMessage.java
  src/main/java/com/example/tripmingle/entity/ChatRoomUser.java
  src/main/java/com/example/tripmingle/port/in/ChatUseCase.java
  src/main/java/com/example/tripmingle/port/out/ChatPersistPort.java
Labels: fix, refactor

#68 [Refactor/SWM-211] 수정, 게시로직 리펙토링, 간단한 나라 API 추가
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/in/CountryController.java
  src/main/java/com/example/tripmingle/adapter/in/UserScheduleController.java
  src/main/java/com/example/tripmingle/adapter/out/FeignClientAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/UserSchedulePersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/CountryFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ScheduleFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/application/service/UserPersonalityService.java
  src/main/java/com/example/tripmingle/application/service/UserScheduleService.java
  src/main/java/com/example/tripmingle/client/MatchingClient.java
  src/main/java/com/example/tripmingle/common/config/WebConfig.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/common/utils/CommonUtils.java
  src/main/java/com/example/tripmingle/dto/etc/ChildBoardCommentDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/CreateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/UpdateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/matching/PostUserPersonalityReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/ParentBoardCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/country/GetCountryInfoDTO.java
  src/main/java/com/example/tripmingle/dto/res/matching/MatchingUserResDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/GetUserScheduleResDTO.java
  src/main/java/com/example/tripmingle/entity/Board.java
  src/main/java/com/example/tripmingle/entity/UserSchedule.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/in/CountryUseCase.java
  src/main/java/com/example/tripmingle/port/in/UserScheduleUseCase.java
  src/main/java/com/example/tripmingle/port/out/FeignClientPort.java
  src/main/java/com/example/tripmingle/port/out/UserSchedulePersistPort.java
  src/main/java/com/example/tripmingle/repository/UserScheduleRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/tripmingle/TripMingleApplicationTests.java
  src/test/resources/application.yml
Labels: feat, refactor

#69 [Feat/SWM-195] 매칭요청API를 pubsub에서 Feign client로 변경 및 헥사고날 아키텍처에 맞는 포트명/메서드명으로 변경
  src/main/java/com/example/tripmingle/adapter/out/BoardMatchingAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/FeignClientAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/ImageStorageAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/MessagePublisher.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/MatchingService.java
  src/main/java/com/example/tripmingle/application/service/S3Service.java
  src/main/java/com/example/tripmingle/client/MatchingClient.java
  src/main/java/com/example/tripmingle/dto/etc/MatchingBoardPublishDTO.java
  src/main/java/com/example/tripmingle/dto/etc/MatchingResDTO.java
  src/main/java/com/example/tripmingle/port/out/BoardMatchingPort.java
  src/main/java/com/example/tripmingle/port/out/FeignClientPort.java
  src/main/java/com/example/tripmingle/port/out/ImageStoragePort.java
  src/test/java/com/example/tripmingle/application/facadeService/MatchingFacadeServiceTest.java
Labels: feat, refactor

#70 [SWM-40] hotfix : self introduction 에 null이 리턴되는경우가 있어서 변경
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
Labels: hotfix

#71 [Refactor] CUD 로직에 대한 반환값 변경, 메서드 및 DTO 통일
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingLikesService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/dto/req/posting/DeletePostingCommentReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/posting/PatchPostingCommentReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/posting/PostPostingCommentReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/DeletePostingCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/GetLikedPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/GetOnePostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/GetPostingsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/PatchPostingCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/PatchPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/PostPostingCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/PostPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/posting/PostingLikeToggleStateResDTO.java
  src/main/java/com/example/tripmingle/entity/Posting.java
  src/main/java/com/example/tripmingle/port/in/PostingCommentUseCase.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
Labels: refactor

#72 [Feat/SWM-208] ElasticSearch를 활용한 검색로직 작성
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/ElasticsearchBoardAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/client/ElasticsearchBoardClient.java
  src/main/java/com/example/tripmingle/common/config/elasticsearch/ElasticsearchFeignConfig.java
  src/main/java/com/example/tripmingle/dto/res/board/SearchBoardResDTO.java
  src/main/java/com/example/tripmingle/entity/Board.java
  src/main/java/com/example/tripmingle/entity/pojo/ElasticsearchResponse.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardPersistPort.java
  src/main/java/com/example/tripmingle/port/out/BoardSearchPort.java
  src/main/java/com/example/tripmingle/repository/BoardRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/tripmingle/TripMingleApplicationTests.java
  src/test/java/com/example/tripmingle/application/facadeService/MatchingFacadeServiceTest.java
  src/test/java/com/example/tripmingle/application/service/BoardServiceTest.java
  src/test/resources/application.yml
Labels: feat

#74 [Feat/SWM-228]
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/MatchingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/application/service/UserPersonalityService.java
  src/main/java/com/example/tripmingle/dto/etc/UpdateBoardDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/CreateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/UpdateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/matching/PostUserPersonalityReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/ToggleStateResDTO.java
  src/main/java/com/example/tripmingle/dto/res/matching/MatchingUserResDTO.java
  src/main/java/com/example/tripmingle/entity/Board.java
  src/main/java/com/example/tripmingle/entity/UserPersonality.java
Labels: feat

#75 [SWM-222] fix : 게시물 생성 로직에서 ES 싱크맞추는 코드를 비동기로 변경
  src/main/java/com/example/tripmingle/adapter/out/ElasticsearchBoardAdapter.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/port/out/BoardSearchPort.java
Labels: refactor
