Repository TripMingle/Back-End-Application, pull requests merged in 2024-06, with the labels that each got.

#6 Feat/#5 빈 메서드 및 패키지구조 생성
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/in/MapController.java
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/BoardPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/application/Service/BoardCommentService.java
  src/main/java/com/example/tripmingle/application/Service/BoardService.java
  src/main/java/com/example/tripmingle/application/Service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/Service/PostingService.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/port/in/AuthUseCase.java
  src/main/java/com/example/tripmingle/port/in/BoardCommentUseCase.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/in/PostingCommentUseCase.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardCommentPersistPort.java
  src/main/java/com/example/tripmingle/port/out/BoardPersistPort.java
  src/main/java/com/example/tripmingle/port/out/PostingCommentPersistPort.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
Labels: feat

#7 응답클래스 설정
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/common/entity/BaseEntity.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/error/ErrorResponse.java
  src/main/java/com/example/tripmingle/common/exception/ExampleException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/common/result/ResultResponse.java
Labels: feat

#8 feat: 카카오 소셜 로그인 구현을 위한 세팅
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/HealthController.java
  src/main/java/com/example/tripmingle/common/config/redis/RedisConfig.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/config/security/customuser/CustomUserDetails.java
  src/main/java/com/example/tripmingle/common/config/security/customuser/CustomUserDetailsService.java
  src/main/java/com/example/tripmingle/common/config/security/filter/CustomLogoutFilter.java
  src/main/java/com/example/tripmingle/common/config/security/filter/JwtFilter.java
  src/main/java/com/example/tripmingle/common/config/security/oauth/WebClientConfig.java
  src/main/java/com/example/tripmingle/common/constants/JwtConstants.java
  src/main/java/com/example/tripmingle/common/utils/JwtUtils.java
  src/main/java/com/example/tripmingle/entity/Refresh.java
  src/main/java/com/example/tripmingle/entity/User.java
  src/main/java/com/example/tripmingle/port/out/RefreshRepository.java
  src/main/java/com/example/tripmingle/port/out/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat

#9 feat: 카카오 소셜 로그인 개발
  .gitignore
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/adapter/out/RefreshPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/UserPersistAdapter.java
  src/main/java/com/example/tripmingle/application/Service/AuthService.java
  src/main/java/com/example/tripmingle/application/Service/KakaoService.java
  src/main/java/com/example/tripmingle/application/facadeService/KakaoAuthFacadeService.java
  src/main/java/com/example/tripmingle/common/config/oauth/KakaoProperties.java
  src/main/java/com/example/tripmingle/common/config/oauth/WebClientConfig.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/config/security/customuser/CustomUserDetailsService.java
  src/main/java/com/example/tripmingle/common/config/security/filter/CustomLogoutFilter.java
  src/main/java/com/example/tripmingle/common/constants/LoginType.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/error/ErrorResponse.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/common/utils/JwtUtils.java
  src/main/java/com/example/tripmingle/dto/etc/KakaoUserInfo.java
  src/main/java/com/example/tripmingle/dto/etc/TokenDTO.java
  src/main/java/com/example/tripmingle/entity/User.java
  src/main/java/com/example/tripmingle/port/in/KakaoAuthUseCase.java
  src/main/java/com/example/tripmingle/port/out/RefreshPort.java
  src/main/java/com/example/tripmingle/port/out/UserPersistPort.java
  src/main/java/com/example/tripmingle/repository/RefreshRepository.java
  src/main/java/com/example/tripmingle/repository/UserRepository.java
Labels: feat

#11 feat: 카카오 로그인 테스트를 위한 카카오 액세스 토큰 발급 로직 개발
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/application/Service/KakaoService.java
  src/main/java/com/example/tripmingle/application/facadeService/KakaoAuthFacadeService.java
  src/main/java/com/example/tripmingle/common/config/oauth/KakaoProperties.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/res/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetBoardsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/KakaoTokenResDTO.java
  src/main/java/com/example/tripmingle/port/in/KakaoAuthUseCase.java
Labels: feat

#12 [Refactor/#44] 소셜로그인 FeignClient로 리팩토링
  build.gradle
  src/main/java/com/example/tripmingle/TripMingleApplication.java
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/application/Service/KakaoService.java
  src/main/java/com/example/tripmingle/common/config/oauth/KakaoProperties.java
  src/main/java/com/example/tripmingle/common/config/oauth/WebClientConfig.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/config/security/filter/JwtFilter.java
  src/main/java/com/example/tripmingle/common/utils/KakaoProperties.java
  src/main/java/com/example/tripmingle/dto/etc/KakaoUserInfo.java
  src/main/java/com/example/tripmingle/dto/res/KakaoLoginResDTO.java
  src/main/java/com/example/tripmingle/entity/User.java
  src/main/java/com/example/tripmingle/port/out/KakaoLoginFeignClientForAccessTokenPort.java
  src/main/java/com/example/tripmingle/port/out/KakaoLoginFeignClientPort.java
  src/main/resources/application.yml
Labels: refactor

#13 [Feat/#46] 포스팅 글 게시 API 개발
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/UserPersistAdapter.java
  src/main/java/com/example/tripmingle/application/Service/PostingService.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/KakaoAuthFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/AuthService.java
  src/main/java/com/example/tripmingle/application/service/BoardCommentService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/application/service/KakaoService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/application/service/UserService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/UserNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/PostPostingReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/PostPostingResDTO.java
  src/main/java/com/example/tripmingle/entity/Posting.java
  src/main/java/com/example/tripmingle/entity/PostingType.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
  src/main/java/com/example/tripmingle/port/out/UserPersistPort.java
  src/main/java/com/example/tripmingle/repository/PostingRepository.java
Labels: feat

#14 [Feat/#47] Posting 게시글 수정 API 개발
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/error/ErrorResponse.java
  src/main/java/com/example/tripmingle/common/exception/PostingNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/PatchPostingReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/PatchPostingResDTO.java
  src/main/java/com/example/tripmingle/entity/Posting.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
  src/main/java/com/example/tripmingle/repository/PostingRepository.java
Labels: feat

#15 [Feat/#48] Posting 삭제 API 개발
  build.gradle
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/DeletePostingReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/DeletePostingResDTO.java
  src/main/java/com/example/tripmingle/entity/Posting.java
  src/main/java/com/example/tripmingle/port/in/PostingCommentUseCase.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
Labels: feat

#17 [Feat/#79] 유저 검증 로직 개발
  src/main/java/com/example/tripmingle/adapter/in/AuthController.java
  src/main/java/com/example/tripmingle/adapter/in/KakaoAuthController.java
  src/main/java/com/example/tripmingle/adapter/out/UserPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/AuthFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/KakaoAuthFacadeService.java
  src/main/java/com/example/tripmingle/application/service/AuthService.java
  src/main/java/com/example/tripmingle/application/service/KakaoService.java
  src/main/java/com/example/tripmingle/common/config/security/SecurityConfig.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/KakaoUserAdditionDetailsReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/ValidateDuplicationReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/ValidateDuplicationResDTO.java
  src/main/java/com/example/tripmingle/entity/User.java
  src/main/java/com/example/tripmingle/port/in/AuthUseCase.java
  src/main/java/com/example/tripmingle/port/in/KakaoAuthUseCase.java
  src/main/java/com/example/tripmingle/port/out/UserPersistPort.java
  src/main/java/com/example/tripmingle/repository/UserRepository.java
Labels: feat

#18 Feat/#71 country 관련 API 개발
  src/main/java/com/example/tripmingle/adapter/in/CountryController.java
  src/main/java/com/example/tripmingle/adapter/out/CountryPersistAdapter.java
  src/main/java/com/example/tripmingle/application/service/CountryService.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/res/GetCountriesResDTO.java
  src/main/java/com/example/tripmingle/entity/Country.java
  src/main/java/com/example/tripmingle/port/in/CountryUseCase.java
  src/main/java/com/example/tripmingle/port/out/CountryPersistPort.java
  src/main/java/com/example/tripmingle/repository/CountryRepository.java
Labels: feat

#19 [Feat/#54] 포스팅 조회관련 로직 개발
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/RefreshPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/UserPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/res/GetAllPostingsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetOnePostingCoCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetOnePostingCommentsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetOnePostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetPreviewPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetSearchPostingsResDTO.java
  src/main/java/com/example/tripmingle/entity/PostingComment.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingCommentPersistPort.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
  src/main/java/com/example/tripmingle/repository/PostingCommentRepository.java
  src/main/java/com/example/tripmingle/repository/PostingRepository.java
  src/main/java/com/example/tripmingle/repository/RefreshRepository.java
  src/main/java/com/example/tripmingle/repository/UserRepository.java
Labels: feat

#21 [Feat/#61] 댓글 CUD 관련 API 개발
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingCommentPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/PostingPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/KakaoService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/PostingCommentInvalidUserException.java
  src/main/java/com/example/tripmingle/common/exception/PostingCommentNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/PostingInvalidUserException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/PatchPostingCommentReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/PostPostingCommentReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/DeletePostingCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/PatchPostingCommentResDTO.java
  src/main/java/com/example/tripmingle/dto/res/PostPostingCommentResDTO.java
  src/main/java/com/example/tripmingle/entity/PostingComment.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingCommentPersistPort.java
  src/main/java/com/example/tripmingle/port/out/PostingPersistPort.java
  src/main/java/com/example/tripmingle/repository/PostingCommentRepository.java
  src/main/java/com/example/tripmingle/repository/PostingRepository.java
  src/main/resources/application.yml
Labels: feat

#23 [Feat/#80] 게시판 좋아요, 북마크 API 구현
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardBoardBookMarkPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/BoardBoardLikesPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardBookMarkService.java
  src/main/java/com/example/tripmingle/application/service/BoardLikesService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/BoardBookMarkNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/BoardLikesNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/res/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetBoardsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/ToggleStateResDTO.java
  src/main/java/com/example/tripmingle/entity/BoardBookMark.java
  src/main/java/com/example/tripmingle/entity/BoardLikes.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardBookMarkPersistPort.java
  src/main/java/com/example/tripmingle/port/out/BoardLikesPersistPort.java
  src/main/java/com/example/tripmingle/repository/BoardBookMarkRepository.java
  src/main/java/com/example/tripmingle/repository/BoardLikesRepository.java
Labels: feat

#24 [Feat/#86] 포스팅 좋아요 관련 API 개발
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingLikesPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingLikesService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/PostingLikesNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/res/GetAllLikedPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetLikedPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/PostingToggleStateResDTO.java
  src/main/java/com/example/tripmingle/entity/PostingLikes.java
  src/main/java/com/example/tripmingle/port/in/PostingUseCase.java
  src/main/java/com/example/tripmingle/port/out/PostingLikesPersistPort.java
  src/main/java/com/example/tripmingle/repository/PostingLikesRepository.java
Labels: feat

#25 [Feat/#89] 내가 작성한 게시글 모아보기 API 개발
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/entity/BoardLikes.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardPersistPort.java
  src/main/java/com/example/tripmingle/repository/BoardRepository.java
Labels: feat

#28 [Feat/#97] 댓글 수 및 로그인된 유저의 좋아요 여부 로직 추가
  src/main/java/com/example/tripmingle/adapter/in/PostingController.java
  src/main/java/com/example/tripmingle/adapter/out/PostingLikesPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingLikesService.java
  src/main/java/com/example/tripmingle/dto/res/GetAllPostingsResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetLikedPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetOnePostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetPreviewPostingResDTO.java
  src/main/java/com/example/tripmingle/dto/res/GetSearchPostingsResDTO.java
  src/main/java/com/example/tripmingle/entity/Posting.java
Labels: feat

#30 [Feat/#108] 게시글 로직 누락건 수정 & 자신의 게시글/댓글만 수정/삭제할 수 있는 로직 작성(feat/#91)
  src/main/java/com/example/tripmingle/adapter/in/BoardController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardBoardBookMarkPersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/BoardBoardLikesPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardBookMarkService.java
  src/main/java/com/example/tripmingle/application/service/BoardCommentService.java
  src/main/java/com/example/tripmingle/application/service/BoardLikesService.java
  src/main/java/com/example/tripmingle/application/service/BoardService.java
  src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
  src/main/java/com/example/tripmingle/application/service/PostingService.java
  src/main/java/com/example/tripmingle/common/utils/UserUtils.java
  src/main/java/com/example/tripmingle/dto/etc/UpdateBoardDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/CreateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/GetAllBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/board/UpdateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardInfoResDTO.java
  src/main/java/com/example/tripmingle/dto/res/board/GetBoardsResDTO.java
  src/main/java/com/example/tripmingle/entity/Board.java
  src/main/java/com/example/tripmingle/entity/BoardBookMark.java
  src/main/java/com/example/tripmingle/entity/BoardLikes.java
  src/main/java/com/example/tripmingle/port/in/BoardUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardBookMarkPersistPort.java
  src/main/java/com/example/tripmingle/port/out/BoardLikesPersistPort.java
  src/main/java/com/example/tripmingle/repository/BoardBookMarkRepository.java
  src/main/java/com/example/tripmingle/repository/BoardLikesRepository.java
  src/main/java/com/example/tripmingle/repository/BoardRepository.java
Labels: feat, fix, refactor

#32 [feat/#116] : 동시성 이슈를 synchronized로 해결하는 로직 작성
  build.gradle
  src/main/java/com/example/tripmingle/application/service/BoardCommentService.java
  src/test/java/com/example/tripmingle/application/service/BoardCommentServiceTest.java
Labels: feat

#33 [Feat/#112] 동시성 이슈를 트랜젝션 격리수준 &비관적락으로 해결해보기
  build.gradle
  src/main/java/com/example/tripmingle/application/service/BoardCommentService.java
  src/main/java/com/example/tripmingle/repository/BoardRepository.java
  src/test/java/com/example/tripmingle/application/service/BoardCommentServiceTest.java
Labels: feat

#34 [feat/#113] redisson을 사용한 분산 락으로 동시성 제어 구현 및 테스트코드 작성
  build.gradle
  src/main/java/com/example/tripmingle/application/service/BoardCommentService.java
  src/main/java/com/example/tripmingle/common/config/redis/RedissonConfig.java
  src/test/java/com/example/tripmingle/application/service/BoardCommentServiceTest.java
Labels: feat

#36 [Feat/swm-118] 게시판일정, 유저일정 CURD API 구현 및 테스트
  src/main/java/com/example/tripmingle/adapter/in/BoardScheduleController.java
  src/main/java/com/example/tripmingle/adapter/in/UserScheduleController.java
  src/main/java/com/example/tripmingle/adapter/out/BoardSchedulePersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/UserSchedulePersistAdapter.java
  src/main/java/com/example/tripmingle/adapter/out/UserTripPersistAdapter.java
  src/main/java/com/example/tripmingle/application/facadeService/BoardFacadeService.java
  src/main/java/com/example/tripmingle/application/facadeService/ScheduleFacadeService.java
  src/main/java/com/example/tripmingle/application/service/BoardScheduleService.java
  src/main/java/com/example/tripmingle/application/service/UserScheduleService.java
  src/main/java/com/example/tripmingle/application/service/UserTripService.java
  src/main/java/com/example/tripmingle/common/error/ErrorCode.java
  src/main/java/com/example/tripmingle/common/exception/BoardScheduleNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/UserScheduleNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/UserTripNotFoundException.java
  src/main/java/com/example/tripmingle/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/example/tripmingle/common/result/ResultCode.java
  src/main/java/com/example/tripmingle/dto/req/board/CreateBoardReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/CreateBoardScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/CreateUserScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/CreateUserTripReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/DeleteBoardScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/DeleteUserScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/ModifyBoardScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/ModifyUserScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/UpdateBoardScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/req/schedule/UpdateUserScheduleReqDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/BoardScheduleResDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/CreateUserTripResDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/GetBoardScheduleResDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/GetUserScheduleResDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/GetUserTripResDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/UserScheduleDTO.java
  src/main/java/com/example/tripmingle/dto/res/schedule/UserScheduleResDTO.java
  src/main/java/com/example/tripmingle/entity/BoardSchedule.java
  src/main/java/com/example/tripmingle/entity/UserSchedule.java
  src/main/java/com/example/tripmingle/entity/UserTrip.java
  src/main/java/com/example/tripmingle/port/in/BoardScheduleUseCase.java
  src/main/java/com/example/tripmingle/port/in/UserScheduleUseCase.java
  src/main/java/com/example/tripmingle/port/out/BoardSchedulePersistPort.java
  src/main/java/com/example/tripmingle/port/out/UserSchedulePersistPort.java
  src/main/java/com/example/tripmingle/port/out/UserTripPersistPort.java
  src/main/java/com/example/tripmingle/repository/BoardScheduleRepository.java
  src/main/java/com/example/tripmingle/repository/UserScheduleRepository.java
  src/main/java/com/example/tripmingle/repository/UserTripRepository.java
Labels: feat
